name: Publish Image

on:
  push:
    branches:
      - master

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: freshollie/tiktok-grouped-likes
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
